-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:27:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemlo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemlo_producto` ;

-- -----------------------------------------------------
-- Schema ejemlo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemlo_producto` ;
USE `ejemlo_producto` ;

-- -----------------------------------------------------
-- Table `ejemlo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemlo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemlo_producto`.`CLIENTE` (
  `dni` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `date` VARCHAR(45) NULL,
  `tlfn` VARCHAR(11) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemlo_producto`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemlo_producto`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `ejemlo_producto`.`PROVEEDOR` (
  `nif` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` TEXT(60) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemlo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemlo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemlo_producto`.`PRODUCTO` (
  `nif` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `PROVEEDOR_nif` INT NOT NULL,
  PRIMARY KEY (`nif`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_nif` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_nif`)
    REFERENCES `ejemlo_producto`.`PROVEEDOR` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemlo_producto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemlo_producto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `ejemlo_producto`.`COMPRA` (
  `CLIENTE_dni` INT NOT NULL,
  `PRODUCTO_nif` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `PRODUCTO_nif`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_nif` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE1_idx` (`CLIENTE_dni` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `ejemlo_producto`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_nif`)
    REFERENCES `ejemlo_producto`.`PRODUCTO` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
